export type Category = "RESIDENTIAL" | "COMMERCIAL" | "TOWNSHIP"

export interface Project {
  id: number
  slug: string
  name: string
  location: string
  category: Category
  thumbnail: string   // used on the sales lounge grid
  images: string[]    // all images for the project detail page
  year: string
  area: string
  brief: string       // 1 sentence client brief
  approach: string    // how EventBrite built it
  outcome: string     // result / impact
}

export const PROJECTS: Project[] = [
  {
    id: 1,
    slug: "rustomjee",
    name: "Rustomjee",
    location: "Dombivli",
    category: "RESIDENTIAL",
    thumbnail: "/images/Rustomjee/1.webp",
    images: Array.from({ length: 15 }, (_, i) => `/images/Rustomjee/${i + 1}.webp`),
    year: "2023",
    area: "8,500 sq. ft.",
    brief: "Design and build a world-class Sales Lounge for Rustomjee's landmark township in Dombivli that reflects the premium lifestyle the project promises.",
    approach: "EventBrite's design team crafted an immersive experience starting with a double-height entrance atrium that opens into a curated journey through the project's lifestyle narrative. We balanced warm timber tones with cool stone surfaces to create a sophisticated yet welcoming environment. A large-format scale model of the township anchors the centre of the space, surrounded by material libraries, lifestyle vignettes, and a dedicated VR bay. The 35,000 sq. ft. fabrication facility produced custom millwork, branded signage, and all furniture in-house, ensuring zero compromise on finish quality.",
    outcome: "The Sales Lounge drove a 40% increase in site visit conversions within the first quarter of launch, with consistent praise from homebuyers for the clarity and premium feel of the experience.",
  },
  {
    id: 2,
    slug: "k-raheja",
    name: "K. Raheja",
    location: "Kanjurmarg, Mumbai",
    category: "COMMERCIAL",
    thumbnail: "/images/K-Raheja/1.webp",
    images: Array.from({ length: 13 }, (_, i) => `/images/K-Raheja/${i + 1}.webp`),
    year: "2023",
    area: "6,200 sq. ft.",
    brief: "Design and build a high-impact Marketing Office for K. Raheja Corp's landmark commercial development in Kanjurmarg that communicates corporate prestige, efficiency, and the aspirational quality of the project to institutional investors and corporate tenants.",
    approach: "EventBrite's design team approached the K. Raheja Marketing Office as a statement of corporate authority. The spatial journey begins with a commanding double-fronted reception clad in large-format stone, immediately establishing the gravitas befitting one of India's most trusted developers. A carefully curated monochromatic palette of charcoal, chalk white, and brushed brass runs through the entire space, ensuring every surface feels purposeful and premium. The central presentation zone features a 14-foot custom-built scale model of the development under a bespoke lighting rig, allowing sales consultants to walk investors through the master plan with cinematic clarity. Private consultation suites lined in warm walnut veneer provide an intimate setting for deal closure, while the open work floor maintains visibility and energy throughout. All joinery, branded signage, wall panels, and furniture were designed and fabricated entirely in-house at EventBrite's 35,000 sq. ft. facility — guaranteeing zero compromise on material quality and a delivery timeline that met the developer's aggressive pre-launch deadline.",
    outcome: "The K. Raheja Marketing Office became an immediate benchmark for commercial project marketing in Mumbai's eastern suburbs. Within the first six weeks of opening, the office facilitated over ₹300 crore in pre-launch bookings and attracted three marquee anchor tenants for the project's retail podium — a testament to the confidence the space inspired in institutional decision-makers visiting for the first time.",
  },
  {
    id: 3,
    slug: "godrej",
    name: "Godrej",
    location: "Karjat, Maharashtra",
    category: "RESIDENTIAL",
    thumbnail: "/images/Godrej/1.webp",
    images: Array.from({ length: 16 }, (_, i) => `/images/Godrej/${i + 1}.webp`),
    year: "2022",
    area: "7,800 sq. ft.",
    brief: "Design an aspirational Sales Lounge for Godrej Properties' nature-integrated residential township in Karjat — a project that needed to transport urban homebuyers into the serenity of the Sahyadri foothills the moment they stepped through the door.",
    approach: "The Godrej Karjat Sales Lounge was designed around a single organizing principle: bringing the outside in. Warm oak panelling, raw stone textures, and a palette drawn directly from the Karjat landscape — terracotta, forest green, and sandy limestone — create an immediate sensory shift from the city. A double-height feature wall clad in live moss anchors the entry experience, while curated ambient sound design fills the space with subtle natural sounds. The central amenity journey guides visitors through lifestyle vignettes — a riverside deck recreation, a forest-view living room, and a terrace garden — before arriving at an interactive township model with responsive LED zone mapping. Soft, diffused lighting throughout avoids the harsh showroom feel and instead evokes the quality of golden-hour light in the hills. Every piece of furniture, millwork, and branded element was fabricated at EventBrite's Mumbai facility and transported to site on a phased delivery schedule to meet the developer's pre-monsoon launch window.",
    outcome: "Phase 1 of the Godrej Karjat township sold out within 3 months of the Sales Lounge opening — well ahead of the developer's internal projections. Homebuyer feedback consistently cited the Sales Lounge experience as a decisive factor in their purchase decision, with many noting it was the first time they could truly visualise life at the project.",
  },
  {
    id: 4,
    slug: "kalpataru-aria",
    name: "Kalpataru – Aria",
    location: "Karjat, Maharashtra",
    category: "TOWNSHIP",
    thumbnail: "/images/sales-lounge/kalpataru-aria-Karjat/1.webp",
    images: Array.from({ length: 8 }, (_, i) => `/images/sales-lounge/kalpataru-aria-Karjat/${i + 1}.webp`),
    year: "2023",
    area: "12,000 sq. ft.",
    brief: "Build a landmark Experience Centre for Kalpataru Aria that conveys the scale, serenity, and premium quality of the township — inspiring confidence in homebuyers from the moment they arrive.",
    approach: "The Kalpataru Aria Experience Centre was designed to be a destination in itself — a space that earns the homebuyer's trust before a single floor plan is discussed. The 12,000 sq. ft. layout opens with a double-height atrium featuring a hand-crafted chandelier installation referencing the township's landscaping motif. Visitors are guided through a series of curated lifestyle zones: a children's amenity recreation, a clubhouse preview lounge, and a sky-deck simulation with floor-to-ceiling perforated screens. The centrepiece is a 20-foot backlit master plan wall with touch-responsive zoning that allows sales consultants to highlight specific towers, amenities, and phase deliveries in real time. Material libraries are integrated into the journey naturally — embedded into walls and surfaces rather than displayed in isolation — so homebuyers absorb specification quality without being lectured to. Soft indirect lighting, acoustic wall panels, and custom fragrance diffusion complete the sensory environment. The entire fitout — from the atrium chandelier to the bespoke reception counter — was designed, engineered, and fabricated in-house at EventBrite's facility.",
    outcome: "Kalpataru Aria became EventBrite's most-visited sales location in FY2023, welcoming over 8,000 homebuyers in the first quarter alone. The project was shortlisted for the CREDAI Best Sales Experience award and is now used internally by Kalpataru Properties as the benchmark design standard for all future township launches.",
  },
  {
    id: 5,
    slug: "oberoi",
    name: "Oberoi",
    location: "Thane",
    category: "RESIDENTIAL",
    thumbnail: "/images/sales-lounge/Oberoi-thane/1.webp",
    images: Array.from({ length: 5 }, (_, i) => `/images/sales-lounge/Oberoi-thane/${i + 1}.webp`),
    year: "2022",
    area: "9,000 sq. ft.",
    brief: "Deliver a luxury sales experience befitting the Oberoi brand in Thane.",
    approach: "Marble, bronze, and bespoke lighting define every surface. A private lounge area for VIP buyers is separated from the main floor by a full-height textured screen.",
    outcome: "Average ticket size increased 18% versus the developer's previous project launch.",
  },
  {
    id: 6,
    slug: "runwal-gardens",
    name: "Runwal Gardens",
    location: "Dombivli",
    category: "TOWNSHIP",
    thumbnail: "/images/sales-lounge/Runwal Gardens-dombivali/1.webp",
    images: Array.from({ length: 9 }, (_, i) => `/images/sales-lounge/Runwal Gardens-dombivali/${i + 1}.webp`),
    year: "2021",
    area: "15,000 sq. ft.",
    brief: "Create a township experience centre for one of Dombivli's largest residential developments.",
    approach: "A 25,000-unit township demands a visitor journey that is educational and inspiring. We created zone-by-zone lifestyle stations across 15,000 sq. ft.",
    outcome: "Welcomed over 50,000 visitors in the first year.",
  },
  {
    id: 7,
    slug: "kalpataru-elitus",
    name: "Kalpataru – Elitus",
    location: "Mulund",
    category: "RESIDENTIAL",
    thumbnail: "/images/sales-lounge/kalpataru-elitus-mulund/1.webp",
    images: Array.from({ length: 6 }, (_, i) => `/images/sales-lounge/kalpataru-elitus-mulund/${i + 1}.webp`),
    year: "2023",
    area: "5,500 sq. ft.",
    brief: "Design an ultra-luxury Sales Lounge for Kalpataru's flagship Mulund project.",
    approach: "Jewellery-store precision in every detail — backlit onyx panels, custom brass hardware, and a private champagne lounge for closings.",
    outcome: "Sold 80% of inventory at launch event.",
  },
  {
    id: 8,
    slug: "ashford",
    name: "Ashford",
    location: "Nahur",
    category: "COMMERCIAL",
    thumbnail: "/images/sales-lounge/Ashford/1.webp",
    images: Array.from({ length: 30 }, (_, i) => `/images/sales-lounge/Ashford/${i + 1}.webp`),
    year: "2022",
    area: "4,800 sq. ft.",
    brief: "Build a project office for Ashford's commercial tower in Nahur.",
    approach: "Efficient, branded, and professional. The space doubles as a working office and a sales showcase.",
    outcome: "Leased 60% of the tower before possession.",
  },
  {
    id: 9,
    slug: "kanchan",
    name: "Kanchan",
    location: "Pune",
    category: "RESIDENTIAL",
    thumbnail: "/images/kanchan-1.webp",
    images: ["/images/kanchan-1.webp", "/images/kanchan-2.webp"],
    year: "2022",
    area: "5,000 sq. ft.",
    brief: "Sales Lounge for Kanchan's mid-segment residential project in Pune.",
    approach: "Value-engineered design that doesn't compromise on aspiration — every rupee on-display.",
    outcome: "Fully subscribed at launch.",
  },
  {
    id: 10,
    slug: "omkar-one",
    name: "Omkar One",
    location: "Majawadi",
    category: "COMMERCIAL",
    thumbnail: "/images/sales-lounge/omkar one/1.webp",
    images: Array.from({ length: 20 }, (_, i) => `/images/sales-lounge/omkar one/${i + 1}.webp`),
    year: "2021",
    area: "3,600 sq. ft.",
    brief: "Marketing office for Omkar's boutique commercial building.",
    approach: "Compact, high-design space with an emphasis on natural light and material quality.",
    outcome: "Fully leased within 6 months.",
  },
  {
    id: 11,
    slug: "kalpataru-avante",
    name: "Kalpataru Avante",
    location: "Hyderabad",
    category: "TOWNSHIP",
    thumbnail: "/images/sales-lounge/Kalpataru Avante- Hyderabad/1.webp",
    images: Array.from({ length: 19 }, (_, i) => `/images/sales-lounge/Kalpataru Avante- Hyderabad/${i + 1}.webp`),
    year: "2023",
    area: "11,000 sq. ft.",
    brief: "Expand EventBrite's footprint to Hyderabad with Kalpataru's first southern township.",
    approach: "Local material palette fused with EventBrite's signature precision execution. Telugu cultural motifs integrated subtly.",
    outcome: "Most successful launch in Kalpataru's Hyderabad history.",
  },
  {
    id: 12,
    slug: "darshan-group",
    name: "Darshan Group",
    location: "Ghatkopar",
    category: "RESIDENTIAL",
    thumbnail: "/images/sales-lounge/Darshan Group- Pestom Sagar-Ghatkopar/1.webp",
    images: Array.from({ length: 12 }, (_, i) => `/images/sales-lounge/Darshan Group- Pestom Sagar-Ghatkopar/${i + 1}.webp`),
    year: "2021",
    area: "4,200 sq. ft.",
    brief: "Sales Lounge for Darshan Group's premium project in Ghatkopar.",
    approach: "Neighbourhood-rooted design with a premium finish — accessible luxury.",
    outcome: "Launched to 1,200+ walk-ins in opening weekend.",
  },
  {
    id: 13,
    slug: "runwal-oyt",
    name: "Runwal – OYT",
    location: "Wadala",
    category: "TOWNSHIP",
    thumbnail: "/images/sales-lounge/runwal-oyt-wadala/1.webp",
    images: Array.from({ length: 4 }, (_, i) => `/images/sales-lounge/runwal-oyt-wadala/${i + 1}.webp`),
    year: "2022",
    area: "8,000 sq. ft.",
    brief: "One Young Township — a youth-first sales experience in Mumbai's mill district.",
    approach: "Bold, graphic, energetic. Colour-blocked zones replace traditional conservative palettes.",
    outcome: "Viral on social media, 200+ organic shares in launch week.",
  },
  {
    id: 14,
    slug: "kalpataru-vivant",
    name: "Kalpataru Vivant",
    location: "Jogeshwari",
    category: "RESIDENTIAL",
    thumbnail: "/images/sales-lounge/kalpataru Vivant- jogeshwari/1.webp",
    images: Array.from({ length: 9 }, (_, i) => `/images/sales-lounge/kalpataru Vivant- jogeshwari/${i + 1}.webp`),
    year: "2023",
    area: "6,800 sq. ft.",
    brief: "Premium Sales Lounge for Kalpataru's Jogeshwari flagship.",
    approach: "Art-gallery curation meets real estate showcase — curated artworks, bespoke furniture, concierge service model.",
    outcome: "Avg. dwell time of 85 minutes — highest in category.",
  },
  {
    id: 15,
    slug: "leo-eminence",
    name: "Leo – Eminence",
    location: "Bandra",
    category: "COMMERCIAL",
    thumbnail: "/images/sales-lounge/leo-eminence-bandra/1.webp",
    images: Array.from({ length: 5 }, (_, i) => `/images/sales-lounge/leo-eminence-bandra/${i + 1}.webp`),
    year: "2023",
    area: "5,200 sq. ft.",
    brief: "Signature commercial showroom in Bandra for Leo Group's flagship tower.",
    approach: "Bandra's creative energy channelled into a bold, statement-making showroom with raw concrete and curated art.",
    outcome: "Attracted marquee brand tenants ahead of completion.",
  },
  {
    id: 16,
    slug: "sunteck",
    name: "Sunteck",
    location: "Thane",
    category: "RESIDENTIAL",
    thumbnail: "/images/sales-lounge/Sunteck/1.webp",
    images: Array.from({ length: 5 }, (_, i) => `/images/sales-lounge/Sunteck/${i + 1}.webp`),
    year: "2022",
    area: "7,000 sq. ft.",
    brief: "Luxury sales experience for Sunteck's Thane entry.",
    approach: "Hotel-lobby DNA — bellhop welcome, café counter, private screening rooms for project films.",
    outcome: "Converted 1 in 3 walk-ins — 3× industry average.",
  },
  {
    id: 17,
    slug: "ground-holding",
    name: "Ground Holding",
    location: "Goregaon",
    category: "COMMERCIAL",
    thumbnail: "/images/sales-lounge/ground holding -Integrated-goregoan/1.webp",
    images: Array.from({ length: 9 }, (_, i) => `/images/sales-lounge/ground holding -Integrated-goregoan/${i + 1}.webp`),
    year: "2022",
    area: "4,000 sq. ft.",
    brief: "Boutique marketing office for Ground Holding's Goregaon commercial project.",
    approach: "Understated luxury — every element custom-made, nothing off-the-shelf.",
    outcome: "Completed on record 18-day timeline.",
  },
  {
    id: 18,
    slug: "omkar",
    name: "Omkar",
    location: "Majaswadi",
    category: "TOWNSHIP",
    thumbnail: "/images/sales-lounge/omkar - majaswadi/1.webp",
    images: Array.from({ length: 7 }, (_, i) => `/images/sales-lounge/omkar - majaswadi/${i + 1}.webp`),
    year: "2021",
    area: "10,500 sq. ft.",
    brief: "Township experience centre for Omkar's large-format Majaswadi development.",
    approach: "Integrated drone footage, AR overlays on the scale model, and live construction webcam feeds.",
    outcome: "3,000+ registrations in first month.",
  },
  {
    id: 19,
    slug: "sayba-pearl-hans",
    name: "Sayba – Pearl Hans",
    location: "Kurla",
    category: "RESIDENTIAL",
    thumbnail: "/images/sales-lounge/Sayba Group- Kurla- Pearl Hans/1.webp",
    images: Array.from({ length: 4 }, (_, i) => `/images/sales-lounge/Sayba Group- Kurla- Pearl Hans/${i + 1}.webp`),
    year: "2021",
    area: "3,800 sq. ft.",
    brief: "Value-segment Sales Lounge for Sayba Group in Kurla.",
    approach: "Maximum aspiration on a tightly managed budget. Smart use of wallcoverings and lighting in lieu of expensive materials.",
    outcome: "Sold out in 45 days.",
  },
  {
    id: 20,
    slug: "kalpataru-srishti",
    name: "Kalpataru – Srishti",
    location: "Mira Road",
    category: "TOWNSHIP",
    thumbnail: "/images/sales-lounge/kalpataru-Srishti-mira road/1.webp",
    images: Array.from({ length: 12 }, (_, i) => `/images/sales-lounge/kalpataru-Srishti-mira road/${i + 1}.webp`),
    year: "2022",
    area: "13,000 sq. ft.",
    brief: "Landmark experience centre for Kalpataru's biggest township on Mira Road.",
    approach: "Designed to handle 500+ daily visitors without feeling rushed. Three parallel visitor journeys flow simultaneously.",
    outcome: "India Real Estate Awards — Best Sales Experience 2022.",
  },
  {
    id: 21,
    slug: "seth-group-one-marina",
    name: "Seth Group – One Marina",
    location: "Marine Lines",
    category: "COMMERCIAL",
    thumbnail: "/images/sales-lounge/seth group-One Marina-marine line/1.webp",
    images: Array.from({ length: 9 }, (_, i) => `/images/sales-lounge/seth group-One Marina-marine line/${i + 1}.webp`),
    year: "2023",
    area: "6,500 sq. ft.",
    brief: "Ultra-premium showroom for Seth Group's iconic Marine Lines tower.",
    approach: "Sea-view orientation, yacht-interior materials, private members' lounge for institutional buyers.",
    outcome: "INR 500Cr+ in bookings at launch event.",
  },
  {
    id: 22,
    slug: "tridhatu-morya",
    name: "Tridhatu Morya",
    location: "Govandi",
    category: "RESIDENTIAL",
    thumbnail: "/images/sales-lounge/Tridhatu morya - govandi/1.webp",
    images: Array.from({ length: 8 }, (_, i) => `/images/sales-lounge/Tridhatu morya - govandi/${i + 1}.webp`),
    year: "2022",
    area: "4,500 sq. ft.",
    brief: "Accessible luxury Sales Lounge for Tridhatu's Govandi project.",
    approach: "First-time-buyer empathy built into every touchpoint — simplified floor plan displays, easy finance integration.",
    outcome: "NPS score of 92 — highest in Tridhatu's history.",
  },
  {
    id: 23,
    slug: "omkar-sereno",
    name: "Omkar Sereno",
    location: "Majawadi",
    category: "TOWNSHIP",
    thumbnail: "/images/sales-lounge/omkar sereno/1.webp",
    images: Array.from({ length: 14 }, (_, i) => `/images/sales-lounge/omkar sereno/${i + 1}.webp`),
    year: "2023",
    area: "9,200 sq. ft.",
    brief: "Sales Lounge for Omkar's luxury Sereno township brand.",
    approach: "Serene, spa-like atmosphere — water features, ambient sound design, scent marketing.",
    outcome: "Shortlisted for CREDAI Best Sales Experience award.",
  },
  {
    id: 24,
    slug: "ukreality",
    name: "Ukreality",
    location: "Jogeshwari",
    category: "COMMERCIAL",
    thumbnail: "/images/sales-lounge/ukreality-jogeshwari/1.webp",
    images: Array.from({ length: 5 }, (_, i) => `/images/sales-lounge/ukreality-jogeshwari/${i + 1}.webp`),
    year: "2023",
    area: "3,200 sq. ft.",
    brief: "Compact but impactful marketing office for Ukreality's Jogeshwari commercial project.",
    approach: "Micro-luxury — small footprint, enormous quality-per-sq-ft ratio.",
    outcome: "Leased 100% at above-market rates.",
  },
]

export function getProjectBySlug(slug: string): Project | undefined {
  return PROJECTS.find(p => p.slug === slug)
}
